#
# Module manifest for module 'stormcenter'
#
# Generated by: neonprimetime
#
# Generated on: 2017-06-21
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'stormcenter.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '2ff9ac5a-c68e-44c2-8f8d-421b39d9d658'

# Author of this module
Author = 'neonprimetime'

# Company or vendor of this module
CompanyName = 'neonprimetime'

# Copyright statement for this module
Copyright = 'The MIT License'

# Description of the functionality provided by this module
Description = 'ISC SANS API with powershell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Get-ISCInfocon', 'Get-ISCHandler', 'Get-ISCBackscatter', 'Get-ISCIp', 'Get-ISCPort',
                'Get-ISCPortDate', 'Get-ISCTopPorts', 'Get-ISCTopIps', 'Get-ISCSources', 'Get-ISCPortHistory',
                'Get-ISCAsnum', 'Get-ISCDailySummary', 'Get-ISCDaily404Summary', 'Get-ISCDaily404Detail',
                'Get-ISCGlossary', 'Get-ISCThreatFeeds', 'Get-ISCThreatFeedsPerDay', 'Get-ISCThreatFeedsByDataFeed',
                'Get-ISCThreatFeedIps', 'Get-ISCThreatFeedByCategory', 'Get-ISCWebHoneypotSummary',
                'Get-ISCWebHoneypotByType', 'Get-ISCOpenIOCLogs', 'Get-ISCMSPatchDay', 'Get-ISCMSPatch',
                'Get-ISCMSPatchCVEs', 'Get-ISCMSPatchKBs'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MIT'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/neonprimetime/isc.sans.edu.api'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}